Fix broken tests - GroovyMock(ServletInputStream.class)
The old pattern of using GroovyMock(ServletInputStream.class) started causing "java.lang.OutOfMemoryError: Java heap space"
¯\_(ツ)_/¯

    Example:
    def is = GroovyMock(ServletInputStream.class)
    is.getBytes() >> {
        mapper.writeValueAsBytes(data)
    }
    request.getInputStream() >> {
        is
    }

   org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 17.
   ...
   Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:244)
	at java.base/java.util.ArrayList.add(ArrayList.java:454)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at org.spockframework.mock.runtime.InteractionScope.addUnmatchedInvocation(InteractionScope.java:80)
	at org.spockframework.mock.runtime.MockController.handle(MockController.java:48)
	at org.spockframework.mock.runtime.GroovyMockInterceptor.intercept(GroovyMockInterceptor.java:79)
	at org.spockframework.mock.runtime.ByteBuddyInterceptorAdapter.interceptNonAbstract(ByteBuddyInterceptorAdapter.java:35)
	at whelk.rest.api.Crud.getRequestBody(Crud.groovy:798)
	at whelk.rest.api.Crud.doPost2(Crud.groovy:642)
	at whelk.rest.api.Crud.doPost(Crud.groovy:623)
	at whelk.rest.api.CrudSpec.POST to / should return 400 Bad Request on empty content(CrudSpec.groovy:865)