fix(batchimport): Bad escape in JSON from getBibDuplicates
getBibDuplicates builds JSON snippets for matching against records in postgres.
It was using groovy.json.StringEscapeUtils.escapeJavaScript
i.e. strings were escaped as javascript string instead of json strings.
So ' was escaped (\') when it shouldn't be.

This in combination with standard_conforming_strings in postgres led to
```
org.postgresql.util.PSQLException: ERROR: invalid input syntax for type json
  detail: Escape sequence "\'" is invalid.

```